# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Pull Request Labeler Github Action Configuration: https://github.com/marketplace/actions/labeler

build:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'
          - '.idea/**/*'
          - 'tools/**/*'
          - '.gitignore'
          - 'azure-pipelines.yml'
          - 'pom.xml'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - 'README.md'

cli:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-cli/**/*'

common:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-common/**/*'

composer:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-composer/**/*'

dist:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-dist/**/*'

runtime:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-runtime/**/*'

e2e-tests:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-e2e-tests/**/*'

migration-tests:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-migration-tests/**/*'

add-ons:
  - changed-files:
      - any-glob-to-any-file:
          - 'flink-cdc-pipeline-model/**/*'
          - 'flink-cdc-pipeline-udf-examples/**/*'

base:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-source-connectors/flink-cdc-base/**/*'

debezium:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-source-connectors/flink-connector-debezium/**/*'

connector-test-util:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-source-connectors/flink-connector-test-util/**/*'

db2-cdc-connector:
  - changed-files:
      - any-glob-to-any-file:
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-connector-db2-cdc/**/*'
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-db2-cdc/**/*'

mongodb-cdc-connector:
  - changed-files:
      - any-glob-to-any-file:
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/**/*'
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-mongodb-cdc/**/*'

mysql-cdc-connector:
  - changed-files:
      - any-glob-to-any-file:
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/**/*'
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-mysql-cdc/**/*'

oceanbase-cdc-connector:
  - changed-files:
      - any-glob-to-any-file:
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oceanbase-cdc/**/*'
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-oceanbase-cdc/**/*'

oracle-cdc-connector:
  - changed-files:
      - any-glob-to-any-file:
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-connector-oracle-cdc/**/*'
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-oracle-cdc/**/*'

postgres-cdc-connector:
  - changed-files:
      - any-glob-to-any-file:
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-connector-postgres-cdc/**/*'
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-postgres-cdc/**/*'

sqlserver-cdc-connector:
  - changed-files:
      - any-glob-to-any-file:
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-connector-sqlserver-cdc/**/*'
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-sqlserver-cdc/**/*'

tidb-cdc-connector:
  - changed-files:
      - any-glob-to-any-file:
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-connector-tidb-cdc/**/*'
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-tidb-cdc/**/*'

vitess-cdc-connector:
  - changed-files:
      - any-glob-to-any-file:
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-connector-vitess-cdc/**/*'
          - 'flink-cdc-connect/flink-cdc-source-connectors/flink-sql-connector-vitess-cdc/**/*'

values-pipeline-connector:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-values/**/*'

mysql-pipeline-connector:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-mysql/**/*'

paimon-pipeline-connector:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/**/*'

kafka-pipeline-connector:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-kafka/**/*'

doris-pipeline-connector:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-doris/**/*'

starrocks-pipeline-connector:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-starrocks/**/*'

elasticsearch-pipeline-connector:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-elasticsearch/**/*'

oceanbase-pipeline-connector:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-oceanbase/**/*'

maxcompute-pipeline-connector:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-maxcompute/**/*'

iceberg-pipeline-connector:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-iceberg/**/*'

postgres-pipeline-connector:
  - changed-files:
      - any-glob-to-any-file: 'flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-postgres/**/*'