-- Licensed to the Apache Software Foundation (ASF) under one or more
-- contributor license agreements.  See the NOTICE file distributed with
-- this work for additional information regarding copyright ownership.
-- The ASF licenses this file to You under the Apache License, Version 2.0
-- (the "License"); you may not use this file except in compliance with
-- the License.  You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

DROP TABLE IF EXISTS TABLE1;

CREATE TABLE TABLE1 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE1 VALUES (1, 'No.1');
DROP TABLE IF EXISTS TABLE2;

CREATE TABLE TABLE2 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE2 VALUES (2, 'No.2');
DROP TABLE IF EXISTS TABLE3;

CREATE TABLE TABLE3 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE3 VALUES (3, 'No.3');
DROP TABLE IF EXISTS TABLE4;

CREATE TABLE TABLE4 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE4 VALUES (4, 'No.4');
DROP TABLE IF EXISTS TABLE5;

CREATE TABLE TABLE5 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE5 VALUES (5, 'No.5');
DROP TABLE IF EXISTS TABLE6;

CREATE TABLE TABLE6 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE6 VALUES (6, 'No.6');
DROP TABLE IF EXISTS TABLE7;

CREATE TABLE TABLE7 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE7 VALUES (7, 'No.7');
DROP TABLE IF EXISTS TABLE8;

CREATE TABLE TABLE8 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE8 VALUES (8, 'No.8');
DROP TABLE IF EXISTS TABLE9;

CREATE TABLE TABLE9 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE9 VALUES (9, 'No.9');
DROP TABLE IF EXISTS TABLE10;

CREATE TABLE TABLE10 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE10 VALUES (10, 'No.10');
DROP TABLE IF EXISTS TABLE11;

CREATE TABLE TABLE11 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE11 VALUES (11, 'No.11');
DROP TABLE IF EXISTS TABLE12;

CREATE TABLE TABLE12 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE12 VALUES (12, 'No.12');
DROP TABLE IF EXISTS TABLE13;

CREATE TABLE TABLE13 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE13 VALUES (13, 'No.13');
DROP TABLE IF EXISTS TABLE14;

CREATE TABLE TABLE14 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE14 VALUES (14, 'No.14');
DROP TABLE IF EXISTS TABLE15;

CREATE TABLE TABLE15 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE15 VALUES (15, 'No.15');
DROP TABLE IF EXISTS TABLE16;

CREATE TABLE TABLE16 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE16 VALUES (16, 'No.16');
DROP TABLE IF EXISTS TABLE17;

CREATE TABLE TABLE17 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE17 VALUES (17, 'No.17');
DROP TABLE IF EXISTS TABLE18;

CREATE TABLE TABLE18 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE18 VALUES (18, 'No.18');
DROP TABLE IF EXISTS TABLE19;

CREATE TABLE TABLE19 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE19 VALUES (19, 'No.19');
DROP TABLE IF EXISTS TABLE20;

CREATE TABLE TABLE20 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE20 VALUES (20, 'No.20');
DROP TABLE IF EXISTS TABLE21;

CREATE TABLE TABLE21 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE21 VALUES (21, 'No.21');
DROP TABLE IF EXISTS TABLE22;

CREATE TABLE TABLE22 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE22 VALUES (22, 'No.22');
DROP TABLE IF EXISTS TABLE23;

CREATE TABLE TABLE23 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE23 VALUES (23, 'No.23');
DROP TABLE IF EXISTS TABLE24;

CREATE TABLE TABLE24 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE24 VALUES (24, 'No.24');
DROP TABLE IF EXISTS TABLE25;

CREATE TABLE TABLE25 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE25 VALUES (25, 'No.25');
DROP TABLE IF EXISTS TABLE26;

CREATE TABLE TABLE26 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE26 VALUES (26, 'No.26');
DROP TABLE IF EXISTS TABLE27;

CREATE TABLE TABLE27 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE27 VALUES (27, 'No.27');
DROP TABLE IF EXISTS TABLE28;

CREATE TABLE TABLE28 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE28 VALUES (28, 'No.28');
DROP TABLE IF EXISTS TABLE29;

CREATE TABLE TABLE29 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE29 VALUES (29, 'No.29');
DROP TABLE IF EXISTS TABLE30;

CREATE TABLE TABLE30 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE30 VALUES (30, 'No.30');
DROP TABLE IF EXISTS TABLE31;

CREATE TABLE TABLE31 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE31 VALUES (31, 'No.31');
DROP TABLE IF EXISTS TABLE32;

CREATE TABLE TABLE32 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE32 VALUES (32, 'No.32');
DROP TABLE IF EXISTS TABLE33;

CREATE TABLE TABLE33 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE33 VALUES (33, 'No.33');
DROP TABLE IF EXISTS TABLE34;

CREATE TABLE TABLE34 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE34 VALUES (34, 'No.34');
DROP TABLE IF EXISTS TABLE35;

CREATE TABLE TABLE35 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE35 VALUES (35, 'No.35');
DROP TABLE IF EXISTS TABLE36;

CREATE TABLE TABLE36 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE36 VALUES (36, 'No.36');
DROP TABLE IF EXISTS TABLE37;

CREATE TABLE TABLE37 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE37 VALUES (37, 'No.37');
DROP TABLE IF EXISTS TABLE38;

CREATE TABLE TABLE38 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE38 VALUES (38, 'No.38');
DROP TABLE IF EXISTS TABLE39;

CREATE TABLE TABLE39 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE39 VALUES (39, 'No.39');
DROP TABLE IF EXISTS TABLE40;

CREATE TABLE TABLE40 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE40 VALUES (40, 'No.40');
DROP TABLE IF EXISTS TABLE41;

CREATE TABLE TABLE41 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE41 VALUES (41, 'No.41');
DROP TABLE IF EXISTS TABLE42;

CREATE TABLE TABLE42 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE42 VALUES (42, 'No.42');
DROP TABLE IF EXISTS TABLE43;

CREATE TABLE TABLE43 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE43 VALUES (43, 'No.43');
DROP TABLE IF EXISTS TABLE44;

CREATE TABLE TABLE44 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE44 VALUES (44, 'No.44');
DROP TABLE IF EXISTS TABLE45;

CREATE TABLE TABLE45 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE45 VALUES (45, 'No.45');
DROP TABLE IF EXISTS TABLE46;

CREATE TABLE TABLE46 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE46 VALUES (46, 'No.46');
DROP TABLE IF EXISTS TABLE47;

CREATE TABLE TABLE47 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE47 VALUES (47, 'No.47');
DROP TABLE IF EXISTS TABLE48;

CREATE TABLE TABLE48 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE48 VALUES (48, 'No.48');
DROP TABLE IF EXISTS TABLE49;

CREATE TABLE TABLE49 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE49 VALUES (49, 'No.49');
DROP TABLE IF EXISTS TABLE50;

CREATE TABLE TABLE50 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE50 VALUES (50, 'No.50');
DROP TABLE IF EXISTS TABLE51;

CREATE TABLE TABLE51 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE51 VALUES (51, 'No.51');
DROP TABLE IF EXISTS TABLE52;

CREATE TABLE TABLE52 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE52 VALUES (52, 'No.52');
DROP TABLE IF EXISTS TABLE53;

CREATE TABLE TABLE53 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE53 VALUES (53, 'No.53');
DROP TABLE IF EXISTS TABLE54;

CREATE TABLE TABLE54 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE54 VALUES (54, 'No.54');
DROP TABLE IF EXISTS TABLE55;

CREATE TABLE TABLE55 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE55 VALUES (55, 'No.55');
DROP TABLE IF EXISTS TABLE56;

CREATE TABLE TABLE56 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE56 VALUES (56, 'No.56');
DROP TABLE IF EXISTS TABLE57;

CREATE TABLE TABLE57 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE57 VALUES (57, 'No.57');
DROP TABLE IF EXISTS TABLE58;

CREATE TABLE TABLE58 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE58 VALUES (58, 'No.58');
DROP TABLE IF EXISTS TABLE59;

CREATE TABLE TABLE59 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE59 VALUES (59, 'No.59');
DROP TABLE IF EXISTS TABLE60;

CREATE TABLE TABLE60 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE60 VALUES (60, 'No.60');
DROP TABLE IF EXISTS TABLE61;

CREATE TABLE TABLE61 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE61 VALUES (61, 'No.61');
DROP TABLE IF EXISTS TABLE62;

CREATE TABLE TABLE62 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE62 VALUES (62, 'No.62');
DROP TABLE IF EXISTS TABLE63;

CREATE TABLE TABLE63 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE63 VALUES (63, 'No.63');
DROP TABLE IF EXISTS TABLE64;

CREATE TABLE TABLE64 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE64 VALUES (64, 'No.64');
DROP TABLE IF EXISTS TABLE65;

CREATE TABLE TABLE65 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE65 VALUES (65, 'No.65');
DROP TABLE IF EXISTS TABLE66;

CREATE TABLE TABLE66 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE66 VALUES (66, 'No.66');
DROP TABLE IF EXISTS TABLE67;

CREATE TABLE TABLE67 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE67 VALUES (67, 'No.67');
DROP TABLE IF EXISTS TABLE68;

CREATE TABLE TABLE68 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE68 VALUES (68, 'No.68');
DROP TABLE IF EXISTS TABLE69;

CREATE TABLE TABLE69 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE69 VALUES (69, 'No.69');
DROP TABLE IF EXISTS TABLE70;

CREATE TABLE TABLE70 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE70 VALUES (70, 'No.70');
DROP TABLE IF EXISTS TABLE71;

CREATE TABLE TABLE71 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE71 VALUES (71, 'No.71');
DROP TABLE IF EXISTS TABLE72;

CREATE TABLE TABLE72 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE72 VALUES (72, 'No.72');
DROP TABLE IF EXISTS TABLE73;

CREATE TABLE TABLE73 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE73 VALUES (73, 'No.73');
DROP TABLE IF EXISTS TABLE74;

CREATE TABLE TABLE74 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE74 VALUES (74, 'No.74');
DROP TABLE IF EXISTS TABLE75;

CREATE TABLE TABLE75 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE75 VALUES (75, 'No.75');
DROP TABLE IF EXISTS TABLE76;

CREATE TABLE TABLE76 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE76 VALUES (76, 'No.76');
DROP TABLE IF EXISTS TABLE77;

CREATE TABLE TABLE77 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE77 VALUES (77, 'No.77');
DROP TABLE IF EXISTS TABLE78;

CREATE TABLE TABLE78 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE78 VALUES (78, 'No.78');
DROP TABLE IF EXISTS TABLE79;

CREATE TABLE TABLE79 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE79 VALUES (79, 'No.79');
DROP TABLE IF EXISTS TABLE80;

CREATE TABLE TABLE80 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE80 VALUES (80, 'No.80');
DROP TABLE IF EXISTS TABLE81;

CREATE TABLE TABLE81 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE81 VALUES (81, 'No.81');
DROP TABLE IF EXISTS TABLE82;

CREATE TABLE TABLE82 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE82 VALUES (82, 'No.82');
DROP TABLE IF EXISTS TABLE83;

CREATE TABLE TABLE83 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE83 VALUES (83, 'No.83');
DROP TABLE IF EXISTS TABLE84;

CREATE TABLE TABLE84 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE84 VALUES (84, 'No.84');
DROP TABLE IF EXISTS TABLE85;

CREATE TABLE TABLE85 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE85 VALUES (85, 'No.85');
DROP TABLE IF EXISTS TABLE86;

CREATE TABLE TABLE86 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE86 VALUES (86, 'No.86');
DROP TABLE IF EXISTS TABLE87;

CREATE TABLE TABLE87 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE87 VALUES (87, 'No.87');
DROP TABLE IF EXISTS TABLE88;

CREATE TABLE TABLE88 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE88 VALUES (88, 'No.88');
DROP TABLE IF EXISTS TABLE89;

CREATE TABLE TABLE89 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE89 VALUES (89, 'No.89');
DROP TABLE IF EXISTS TABLE90;

CREATE TABLE TABLE90 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE90 VALUES (90, 'No.90');
DROP TABLE IF EXISTS TABLE91;

CREATE TABLE TABLE91 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE91 VALUES (91, 'No.91');
DROP TABLE IF EXISTS TABLE92;

CREATE TABLE TABLE92 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE92 VALUES (92, 'No.92');
DROP TABLE IF EXISTS TABLE93;

CREATE TABLE TABLE93 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE93 VALUES (93, 'No.93');
DROP TABLE IF EXISTS TABLE94;

CREATE TABLE TABLE94 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE94 VALUES (94, 'No.94');
DROP TABLE IF EXISTS TABLE95;

CREATE TABLE TABLE95 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE95 VALUES (95, 'No.95');
DROP TABLE IF EXISTS TABLE96;

CREATE TABLE TABLE96 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE96 VALUES (96, 'No.96');
DROP TABLE IF EXISTS TABLE97;

CREATE TABLE TABLE97 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE97 VALUES (97, 'No.97');
DROP TABLE IF EXISTS TABLE98;

CREATE TABLE TABLE98 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE98 VALUES (98, 'No.98');
DROP TABLE IF EXISTS TABLE99;

CREATE TABLE TABLE99 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE99 VALUES (99, 'No.99');
DROP TABLE IF EXISTS TABLE100;

CREATE TABLE TABLE100 (
    ID INT NOT NULL PRIMARY KEY,
    VERSION VARCHAR(17)
);

INSERT INTO TABLE100 VALUES (100, 'No.100');
