/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.cdc.connectors.mysql.source.utils;

import org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.JsonProcessingException;
import org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.ObjectMapper;

import io.debezium.data.Envelope;
import io.debezium.relational.TableId;
import io.debezium.relational.history.HistoryRecord;
import org.apache.kafka.connect.data.Struct;
import org.apache.kafka.connect.source.SourceRecord;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static io.debezium.connector.AbstractSourceInfo.TABLE_NAME_KEY;
import static org.apache.flink.cdc.connectors.mysql.debezium.dispatcher.EventDispatcherImpl.HISTORY_RECORD_FIELD;

/** Utility class for handling gh-ost/pt-osc online schema change events. */
public class OnlineSchemaChangeUtils {

    private static final Logger LOG = LoggerFactory.getLogger(OnlineSchemaChangeUtils.class);

    private OnlineSchemaChangeUtils() {}

    /**
     * Pattern matching gh-ost shadow table ({@code _<name>_gho}) and pt-osc new table ({@code
     * _<name>_new}), which carry the actual ALTER DDL during an online schema change.
     */
    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    private static final Pattern OSC_TABLE_ID_PATTERN = Pattern.compile("^_(.*)_(gho|new)$");

    /**
     * Pattern matching gh-ost delete table ({@code _<name>_del}) and pt-osc old table ({@code
     * _<name>_old}), which are the temporary backup tables created during an online schema change.
     */
    private static final Pattern OSC_TEMP_TABLE_ID_PATTERN = Pattern.compile("^_(.*)_(del|old)$");

    /**
     * Checks whether the given source record is a gh-ost/pt-osc initiated schema change event by
     * inspecting the ALTER DDL statement targeting a shadow/new table.
     *
     * <p>There will be these schema change events generated in total during one transaction.
     *
     * <p>gh-ost:
     *
     * <pre>
     * DROP TABLE IF EXISTS `db`.`_tb1_gho`
     * DROP TABLE IF EXISTS `db`.`_tb1_del`
     * DROP TABLE IF EXISTS `db`.`_tb1_ghc`
     * create /* gh-ost *&#47; table `db`.`_tb1_ghc` ...
     * create /* gh-ost *&#47; table `db`.`_tb1_gho` like `db`.`tb1`
     * alter /* gh-ost *&#47; table `db`.`_tb1_gho` add column c varchar(255)
     * alter /* gh-ost *&#47; table `db`.`_tb1_gho` AUTO_INCREMENT=N  (only present when the table has an AUTO_INCREMENT column)
     * create /* gh-ost *&#47; table `db`.`_tb1_del` ...
     * DROP TABLE IF EXISTS `db`.`_tb1_del`
     * rename /* gh-ost *&#47; table `db`.`tb1` to `db`.`_tb1_del`
     * rename /* gh-ost *&#47; table `db`.`_tb1_gho` to `db`.`tb1`
     * DROP TABLE IF EXISTS `db`.`_tb1_ghc`
     * DROP TABLE IF EXISTS `db`.`_tb1_del`
     * </pre>
     *
     * <p>pt-osc:
     *
     * <pre>
     * CREATE TABLE `db`.`_test_tb1_new`
     * ALTER TABLE `db`.`_test_tb1_new` add column c varchar(50)
     * CREATE TRIGGER `pt_osc_db_test_tb1_del`...
     * CREATE TRIGGER `pt_osc_db_test_tb1_upd`...
     * CREATE TRIGGER `pt_osc_db_test_tb1_ins`...
     * ANALYZE TABLE `db`.`_test_tb1_new` /* pt-online-schema-change *&#47;
     * RENAME TABLE `db`.`test_tb1` TO `db`.`_test_tb1_old`, `db`.`_test_tb1_new` TO `db`.`test_tb1`
     * DROP TABLE IF EXISTS `_test_tb1_old` /* generated by server *&#47;
     * DROP TRIGGER IF EXISTS `db`.`pt_osc_db_test_tb1_del`
     * DROP TRIGGER IF EXISTS `db`.`pt_osc_db_test_tb1_upd`
     * DROP TRIGGER IF EXISTS `db`.`pt_osc_db_test_tb1_ins`
     * </pre>
     *
     * <p>Among all these, only the ALTER statement targeting the {@code _gho}/{@code _new} table is
     * stored temporarily, and emitted when the subsequent RENAME TABLE event arrives.
     */
    public static boolean isOnLineSchemaChangeEvent(SourceRecord record) {
        if (!RecordUtils.isSchemaChangeEvent(record)) {
            return false;
        }
        Struct value = (Struct) record.value();
        try {
            String ddl =
                    OBJECT_MAPPER.readTree(value.getString(HISTORY_RECORD_FIELD))
                            .get(HistoryRecord.Fields.DDL_STATEMENTS)
                            .asText()
                            .toLowerCase();
            if (ddl.startsWith("alter")) {
                String tableName =
                        value.getStruct(Envelope.FieldName.SOURCE).getString(TABLE_NAME_KEY);
                return OSC_TABLE_ID_PATTERN.matcher(tableName).matches();
            }
            return false;
        } catch (JsonProcessingException e) {
            return false;
        }
    }

    /**
     * Parses a gh-ost/pt-osc RENAME TABLE event and returns the original (user-facing) table name
     * if the event represents the completion of an online schema change.
     *
     * @return the original table name if the record is an OSC completion rename, or {@link
     *     Optional#empty()} otherwise.
     */
    public static Optional<String> parseOnLineSchemaRenameEvent(SourceRecord record) {
        if (!RecordUtils.isSchemaChangeEvent(record)) {
            return Optional.empty();
        }
        Struct value = (Struct) record.value();

        try {
            String ddl =
                    OBJECT_MAPPER.readTree(value.getString(HISTORY_RECORD_FIELD))
                            .get(HistoryRecord.Fields.DDL_STATEMENTS)
                            .asText()
                            .toLowerCase();
            if (ddl.startsWith("rename table") || ddl.startsWith("rename /* gh-ost */ table")) {
                LOG.info("Checking if DDL might be an OSC renaming event... {}", ddl);
                List<String> tableNames =
                        Arrays.asList(
                                value.getStruct(Envelope.FieldName.SOURCE)
                                        .getString(TABLE_NAME_KEY)
                                        .split(","));
                if (tableNames.size() != 2) {
                    LOG.info(
                            "Table name {} is malformed, skip it.",
                            value.getStruct(Envelope.FieldName.SOURCE).getString(TABLE_NAME_KEY));
                    return Optional.empty();
                }

                String renamedFromTableName =
                        Collections.min(tableNames, Comparator.comparingInt(String::length));
                String renamedToTableName =
                        Collections.max(tableNames, Comparator.comparingInt(String::length));

                LOG.info(
                        "Determined the shorter TableId {} is the renaming source.",
                        renamedFromTableName);
                LOG.info(
                        "Determined the longer TableId {} is the renaming target.",
                        renamedToTableName);

                if (OSC_TEMP_TABLE_ID_PATTERN.matcher(renamedToTableName).matches()) {
                    LOG.info(
                            "Renamed to TableId name {} matches OSC temporary TableId pattern, yield {}.",
                            renamedToTableName,
                            renamedFromTableName);
                    return Optional.of(renamedFromTableName);
                }

                LOG.info(
                        "Renamed to TableId {} does not match any RegEx pattern, skip it.",
                        renamedToTableName);
            }
            return Optional.empty();
        } catch (JsonProcessingException e) {
            LOG.warn("Failed to parse schema change event {}", value, e);
            return Optional.empty();
        }
    }

    /**
     * Peels out a gh-ost/pt-osc mangled {@link TableId} back to the original user-facing one.
     *
     * <p>For example, {@code _customers_gho} → {@code customers}, {@code _orders_new} → {@code
     * orders}.
     */
    public static TableId peelTableId(TableId tableId) {
        Matcher matchingResult = OSC_TABLE_ID_PATTERN.matcher(tableId.table());
        if (matchingResult.matches()) {
            return new TableId(tableId.catalog(), tableId.schema(), matchingResult.group(1));
        }
        return tableId;
    }
}
