# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# https://github.com/actions/stale
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 0 * * *'
permissions:
  # Stale recommended permissions
  pull-requests: write
  issues: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          operations-per-run: 1000
          # Stale Issues
          days-before-issue-stale: 0
          days-before-issue-close: 0
          stale-issue-message: >
            As required by Apache Flink, please report bugs or new features on Apache Jira
            under the project Flink using component tag Flink CDC. You must have a JIRA account in order to log cases and issues.
            If you don’t have an ASF JIRA account, you can request one at the ASF Self-serve portal,
            account creation requires review by the PMC member of the application project, which normally takes one to two working days to be approved.
          close-issue-message: >
            This issue has been closed because Flink CDC doesn't use GitHub issue trackers.
          # Stale PRs
          days-before-pr-stale: 120
          days-before-pr-close: 60
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had recent
            activity for 120 days. It will be closed in 60 days if no further activity occurs.
          close-pr-message: >
            This pull request has been closed because it has not had recent activity. You could reopen it
            if you try to continue your work, and anyone who are interested in it are encouraged to continue
            work on this pull request.
          # Auto-remove stale has conflicts with existing approve label workflows
          # and will result in Stale label missing.
          remove-pr-stale-when-updated: false
          remove-issue-stale-when-updated: false
          # Allow pinning issues and PRs that is not meant to be closed automatically
          exempt-issue-labels: "pinned"
          exempt-pr-labels: "pinned"